name: self-hosted

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  linux:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - run: sudo bin/build-linux.sh

    - run: |
        ./rubyc-linux-x64 -v
        ./rubyc-linux-x64 -V

    - uses: actions/upload-artifact@v2
      with:
        name: rubyc-linux-x64
        path: rubyc-linux-x64

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1

    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.16.2'

    - run: brew install squashfs

    - run: bin/build-macos.sh

    - run: |
        ./rubyc-darwin-x64 -v
        ./rubyc-darwin-x64 -V

    - uses: actions/upload-artifact@v2
      with:
        name: rubyc-darwin-x64
        path: rubyc-darwin-x64

  linux-packed-mn:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    needs: linux
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        repository: metanorma/packed-mn

    - run: bundle update --all

    - run: sudo apt-get update && sudo apt-get -y -q install squashfs-tools bison flex texinfo

    - run: |
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100

    - run: |
        curl -Lks 'https://git.io/rg-ssl' | ruby
        echo "perl -v: $(perl -v)"
        echo "clang -v: $(clang -v)"
        echo "clang++ -v: $(clang -v)"

    - uses: actions/download-artifact@v2
      with:
        name: rubyc-linux-x64

    - run: mv rubyc-linux-x64 rubyc && chmod +x rubyc

    - run: make build/metanorma
      timeout-minutes: 180
      # https://trac.sagemath.org/ticket/19762
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++

    - run: build/metanorma help

    - uses: actions/upload-artifact@v2
      with:
        name: metanorma-linux
        path: build/metanorma

  linux-test:
    needs: linux-packed-mn
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.ignore-errors }}
    strategy:
      fail-fast: false
      matrix:
        os: [ self-hosted, ubuntu-18.04, ubuntu-20.04 ]
        ignore-errors: [ false ]
        test-flavor:
          - iso
    steps:
      - uses: actions/checkout@v2
        with:
          repository: metanorma/packed-mn

      - uses: actions/download-artifact@v2
        with:
          name: metanorma-linux
          path: build

      - run: chmod +x build/metanorma

      - run: make test-flavor
        env:
          GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
          TEST_FLAVOR: ${{ matrix.test-flavor }}

      - uses: actions/upload-artifact@v2
        with:
          name: site-linux
          path: site/**

  macos-packed-mn:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    needs: macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: metanorma/packed-mn

      - uses: ruby/setup-ruby@v1
        with:
          bundler: 2.2.3
          bundler-cache: true

      - run: bundle update --all

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.16.2'

      - run: |
          curl -Lks 'https://git.io/rg-ssl' | ruby
          echo "perl -v: $(perl -v)"
          echo "clang -v: $(clang -v)"
          echo "clang++ -v: $(clang -v)"

      - run: brew install squashfs

      - uses: actions/download-artifact@v2
        with:
          name: rubyc-darwin-x64

      - run: mv rubyc-darwin-x64 rubyc && chmod +x rubyc

      - run: make build/metanorma
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer

      - run: build/metanorma help

      - uses: actions/upload-artifact@v2
        with:
          name: metanorma-macos
          path: build/metanorma

  macos-test:
    needs: macos-packed-mn
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.ignore-errors }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-10.15 ]
        ignore-errors: [ false ]
        test-flavor:
          - iso
        include:
          # macos-11.0 looks not working
          - test-flavor: iso
            ignore-errors: true
            os: macos-11.0
    steps:
      - uses: actions/checkout@v2
        with:
          repository: metanorma/packed-mn

      - uses: actions/download-artifact@v2
        with:
          name: metanorma-macos
          path: build

      - run: chmod a+x build/metanorma

      - run: make test-flavor
        env:
          GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
          TEST_FLAVOR: ${{ matrix.test-flavor }}

      - uses: actions/upload-artifact@v2
        with:
          name: site-macos
          path: site/**

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [linux, macos]
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: rubyc-linux-x64

    - uses: actions/download-artifact@v2
      with:
        name: rubyc-darwin-x64

    - run: ls -lah

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          rubyc-linux-x64
          rubyc-darwin-x64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
